### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by tgandee79** [chrisgame/ember-by-example#5]
Can you document, in the README, the cli-addons and NPM libraries you use?  I was curious about component `percentage-gauge` and I had to find it in `package.json`.  The repo is a great example of routing with nested routes and using services.  Really good for a beginner.

**Comment by chrisgame** [comment]
Hey Todd, glad it helped. 
Would this improve the read me from your point of view? I'll add a better one to the gauge repo as well.

**Comment by tgandee79** [comment]
That helps a lot.  Thanks.

**Comment by tgandee79** [comment]
You should probably close this when you merge the PR.
